# Simple deployment used to deploy and manage the app in nigelpoulton/ps-web:1.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bombdisposal-deploy
  labels:
    app: bombdisposal
spec:
  selector:
    matchLabels:
      app: bombdisposal
  replicas: 5
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: bombdisposal
    spec: 
      terminationGracePeriodSeconds: 1
      containers:
      - name: bombdisposal-pod
        image: planetsugar/bombdisposal:{BUILD_ID}
        imagePullPolicy: Always
        ports:
        - containerPort: 8081