# Simple deployment used to deploy and manage the app in nigelpoulton/getting-started-k8s:1.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bombdisposal-deploy
  labels:
    app: bombdisposal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bombdisposal
  template:
    metadata:
      labels:
        app: bombdisposal
    spec: 
      terminationGracePeriodSeconds: 1
      containers:
      - name: bombdisposal-pod
        image: planetsugar/bombdisposal
        imagePullPolicy: Always
        ports:
        - containerPort: 8080