apiVersion: apps/v1
kind: Deployment
metadata:
  name: bombdisposal-deploy
  labels:
    app: bombdisposal
spec:
  selector:
    matchLabels:
      app: bombdisposal
  replicas: 10
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: bombdisposal
    spec: 
      terminationGracePeriodSeconds: 1
      containers:
      - name: bombdisposal-pod
        image: 192.168.0.252:5000/planetsugar/bombdisposal:{BUILD_ID}
        imagePullPolicy: Always
        ports:
        - containerPort: 8081