apiVersion: v1
kind: Service
metadata:
  name: bombdisposal-nodeport
spec:
  type: NodePort
  ports:
  - port: 81
    targetPort: 8081
    nodePort: 31112
    protocol: TCP
  selector:
    app: bombdisposal